[tool.poetry]
name = "archbuild"
version = "0.1.0"
description = "Arch Linux build automation with Buildbot"
authors = ["Maxime Gauduin <alucryd@archlinux.org>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
buildbot = {version = "^2.4", extras = ["bundle", "tls"]}
buildbot-worker = "^2.4"
buildbot-www = "^2.4"
psutil = "^5.6"
service_identity = "^18.1"

[tool.poetry.dev-dependencies]
black = "=19.10b0"
isort = "^4.3"
pylint = "^2.3"
rope = "^0.14.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
