[tool.poetry]
name = "archbuild"
version = "0.1.0"
description = "Arch Linux build automation with Buildbot"
authors = ["Maxime Gauduin <alucryd@archlinux.org>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.7"
buildbot = "^2.4"
buildbot-worker = "^2.4"
buildbot-www = "^2.4"
service_identity = "^18.1"
psutil = "^5.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
