# buildbot url
url: http://localhost:8010
# master directories
pkgbuilddir: /path/to/pkgbuilds
srcdir: /path/to/srcs
pkgdir: /path/to/pkgs
# email reports
mail_reports: False
mail_host: localhost
mail_user: buildbot
mail_password: password
mail_sender: buildbot@localhost
mail_recipients:
  - user1@localhost
  - user2@localhost
# authentication
admins:
  username: password
oauth: True
oauth_openid_configuration_uri: https://auth.domain.tld/.well-known/openid-configuration
# package repos
repos:
  - name: core
    pkgs:
      - name: pkg1
      - name: pkg2
        testing: True
  - name: extra
    pkgs:
      - name: pkg3
      - name: pkg4
        depends:
          - pkg1
