# buildbot url
url: http://localhost:8010
# master directories
pkgbuilddir: /path/to/pkgbuilds
srcdir: /path/to/srcs
pkgdir: /path/to/pkgs
sshdir: /path/to/ssh/mountpoint # optional
# worker directories
repodir: /path/to/public/html
# repository suffix
suffix: archbuild
# sign packages
gpg_sign: False
# email reports
mail_reports: False
sender: buildbot@localhost
recipients:
 - user1@localhost
 - user2@localhost
# authentication
admins:
  username: password
# repositories
repos:
  - extra
  - testing
  - staging
  - multilib
  - multilib-testing
  - multilib-staging
# package groups
groups:
  -
    name: community
    repo: extra
    pkgs:
    - name: pkg1
    - name: pkg2
      repo: multilib
  -
    name: packages
    repo: extra
    pkgs:
      - name: pkg3
      - name: pkg4
        depends:
          - pkg1
